### ISSUE TITLE
 get this error : throw new TelegramError({ error_code: 401, description: 'Bot Token is required' })

### ISSUE THREAD

**Issue by masihtehrani** [startingupteams/podcast#13]
/Users/mahm0ud/Develop/podcast/node_modules/telegraf/core/network/client.js:211
      throw new TelegramError({ error_code: 401, description: 'Bot Token is required' })
      ^

Error: 401: Bot Token is required
    at Telegram.callApi (/Users/mahm0ud/Develop/podcast/node_modules/telegraf/core/network/client.js:211:13)
    at Telegram.getUpdates (/Users/mahm0ud/Develop/podcast/node_modules/telegraf/telegram.js:28:17)
    at Telegraf.fetchUpdates (/Users/mahm0ud/Develop/podcast/node_modules/telegraf/telegraf.js:129:19)
    at Telegraf.startPolling (/Users/mahm0ud/Develop/podcast/node_modules/telegraf/telegraf.js:73:12)
    at Object.<anonymous> (/Users/mahm0ud/Develop/podcast/src/index.js:5:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error Command failed with exit code 1.

**Comment by masihtehrani** [comment]
you create .env on root project and add below text 
BOT_TOKEN=YOUR_TOKEN_TELEGRAM_BOT

and add on your terminal 
export BOT_TOKEN=YOUR_TOKEN_TELEGRAM_BOT
